### PR TITLE
Browserify Support

### PR DESCRIPTION
**Pull request by nordfjord**
I added support for browserify

### CODE REVIEW

**Comment by wilmoore** [comment]
Cool...thanks.

**Comment by geroyche** [comment]
@wilmoore 
this PR is of limited utility, mainly because no
```
npm version patch
npm publish
```

was done.
i.e.: it was version 3.0.0 before and it is still version 3.0.0 after, which is why I do not get this version when running
`npm install cometd-jquery`
but the version prior to this.

**Comment by nordfjord** [comment]
Hello @geroyche, thank you for commenting on my five year old PR in order to speak of its utility.

1. Versioning and publishing is on package maintainers to do and not on PR authors

Even if I wanted to publish a new version of the package I do not own it and therefore do not have access to such commands.

Furthermore, why not open an issue in stead of necroing an old PR?

And even still, if you want to use this code then why not do a bit of googling and find out that NPM supports github repositories as a target!

See the docs https://docs.npmjs.com/cli/install

Now I do suggest that you open an actual issue with the c.metd-jquery repo to suggest a publish.

Goodbye.

**Comment by geroyche** [comment]
okay, so I am actually rather new to interacting with GitHub instead of just downloading things and being done with it.
apparently I haven't gotten it right, apologies for that.
i wasn't actually talking you to (again, that is not meant in a mean sense), at least i thought so. i commented on this PR at https://github.com/wilmoore/cometd-jquery/, which as far as i can tell is  the original repo, and belongs to the package maintainer? no?

**Comment by nordfjord** [comment]
Okay.

A pull request is usually a change implemented by someone other than the repo owner and submitted. In other words a PR does not have to belong to a repo owner.

If what you need is for the repositories master branch to be published on npm with a version bump the correct place to ask for that is an issue.

Commenting on already merged PRs is unusual. Mentioning an old PR in a comment is not. e.g.

> I noticed that the repo has not been published since PR #1, is that something that could be fixed?

In the end I took offense to your description of my work having “limited utility”. Since you used that description on a comment directly on my work.

**Comment by geroyche** [comment]
thank your for the explanation, and sorry again.
in particular "limited utitily" did decidedly not refer to the content of the PR, but the effects of the PR in terms of package distribution to users. on the contrary, the content of the PR it's what I was looking for, but failed to get when installing per npm.

i will stop here, and hope that I was able to clarify this.

**Comment by nordfjord** [comment]
My pleasure, If you really want to run this code you can install it using npm via:

```sh
$ npm install git+https://github.com/wilmoore/cometd-jquery.git#73f541a914d9263197c39218cfe6ac0b0ee0ebba
```

Using the github repo rather than the npm package to install (I think that's what I ended up doing 5 years ago).

I'm sorry for reading too harshly into your comment.

**Pull request merged**
